# Generated by Django 4.2.1 on 2023-05-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatedapp', '0001_initial'),
        ('account', '0003_alter_profile_department_alter_profile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relatedapp.department'),
        ),
    ]
