# Generated by Django 4.2.1 on 2023-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_resettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
