# Generated by Django 4.2.1 on 2023-05-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_review_phote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='phote',
            new_name='photo',
        ),
    ]
