# Generated by Django 4.2.1 on 2023-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_phote_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='acceptance_rate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='category',
            field=models.CharField(choices=[('University', 'University'), ('Polytechnic', 'Polytechnic'), ('Colledge_of_Education', 'Colledge_of_Education')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='date_founded',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='file_proof',
            field=models.FileField(blank=True, null=True, upload_to='School_file_proofs/'),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='graduation_rate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='linkedln',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='no_of_campuses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='no_of_departments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='no_of_faculties',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='sub_category',
            field=models.CharField(choices=[('Federal', 'Federal'), ('State', 'State'), ('Private', 'Private'), ('Non-Profit', 'Non-Profit')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
